### ISSUE TITLE
Adicionar possibilidade de alterar o usuário

### ISSUE THREAD

**Issue by yknsilva** [luis-olivetti/meu-dia-para-task#1]
## Problema

A planilha hoje está sendo gerada com um valor fixo na coluna do usuário.

## Solução

Possibilitar que o nome do usuário seja informado e, então, o valor seja reaproveitado durante a gravação dos registros.

**Comment by luis-olivetti** [comment]
Oi Yuri, disponibilizado isso nesta versão:
https://github.com/luis-olivetti/meu-dia-para-task/releases/tag/v1.1.0

Obrigado pelo comentário.
